apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: spetrovskaaa/spring-boot-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_DATA_MONGODB_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET_KEY

