version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db  # This mounts a local directory to persist MongoDB data

  app:
    image: spring-boot-app  # Make sure you've built your Spring Boot image already
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/testdb
    depends_on:
      - mongodb

