apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: my-namespace
data:
  # Example configuration; adjust as needed.
  example.conf: |
    # MongoDB configuration example
    net:
      bindIp: 0.0.0.0

