apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: my-namespace
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4="       # "admin" base64 encoded
  MONGO_INITDB_ROOT_PASSWORD: "cGFzc3dvcmQ="   # "password" base64 encoded

